<a href="https://colab.research.google.com/github/zomorrodi/Datasets/blob/master/Lab_3_std4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

data = np.array(
    [[0.08,0.72,1.0],
     [0.01,1.00,0.0],
     [0.26,0.58,1.0],
     [0.35,0.95,0.0],
     [0.45,0.15,1.0],
     [0.60,0.30,1.0],
     [0.70,0.65,0.0],
     [0.92,0.45,0.0]]
)
w1 = [1.00, -1.00]
w2 = [1.00, -1.00]
arr1 =  np.array([w1,w2])
arr2 =  np.array([w1])
b1 = 0.20
b2 = 0.20

def sigmoid(x):
    return 1.0/ (1.0 + np.exp(-x))
  
def sigmoid_derivative(x):
    sigmoid_fx = sigmoid(x)
    return sigmoid_fx * (1 - sigmoid_fx)    

def loss(predicted, actual):
    return (predicted - actual) ** 2
 
def loss_derivative(predicted, actual):
    return 2 * (predicted - actual)

def acc(data, w1, w2, b1, b2):
    data_x = data[:,:-1]
    data_y = data[:, -1]
    
    tmp1 = sigmoid(np.dot(w1, data_x.T) + b1)
    
    p = np.where(sigmoid(np.dot(w2, tmp1) + b2) >= 0.5, 1.0, 0.0)
    return np.sum(p == data_y) / data.shape[0]

print('\nNOT RANDOM DATA:')

def train(data, w1, w2, b1, b2, epoch_number, rate):
    
    for epoch in range(1, epoch_number+1):
        data_x = data[:,:-1]
        data_y = data[:, -1]
        
        tmp1 = np.dot(w1, data_x.T) + b1
        tmp1_der = sigmoid_derivative(tmp1)
        pred1 = sigmoid(tmp1)
        
        
        tmp2 = np.dot(w2, pred1) + b2
        tmp2_der = sigmoid_derivative(tmp2)
        pred2 = sigmoid(tmp2)

        loss_der = loss_derivative(pred2, data_y)
        update_der = loss_derivative(pred2, data_y) * tmp2_der
        
        w1_update = np.dot(np.dot((update_der).T, w2).T * tmp1_der, data_x) * rate 
        w1 -= w1_update
        w2_update = np.dot(update_der, pred1.T) * rate
        w2 -= w2_update
        b1_update = np.dot((update_der).T,w2).T * np.sum(tmp1_der) * rate
        b1 -= b1_update
        b2_update = np.sum(update_der) * rate
        b2 -= b2_update

        print('\nEpoch:', epoch)
        print('-> Acc =', acc(data, w1, w2, b1, b2))

    return w1, w2, b1, b2

train(data, arr1, arr2, b1, b2, 500, 0.001)


NOT RANDOM DATA:

Epoch: 1
-> Acc = 0.5

Epoch: 2
-> Acc = 0.5

Epoch: 3
-> Acc = 0.5

Epoch: 4
-> Acc = 0.5

Epoch: 5
-> Acc = 0.5

Epoch: 6
-> Acc = 0.5

Epoch: 7
-> Acc = 0.5

Epoch: 8
-> Acc = 0.5

Epoch: 9
-> Acc = 0.5

Epoch: 10
-> Acc = 0.5

Epoch: 11
-> Acc = 0.5

Epoch: 12
-> Acc = 0.5

Epoch: 13
-> Acc = 0.5

Epoch: 14
-> Acc = 0.5

Epoch: 15
-> Acc = 0.5

Epoch: 16
-> Acc = 0.5

Epoch: 17
-> Acc = 0.5

Epoch: 18
-> Acc = 0.5

Epoch: 19
-> Acc = 0.5

Epoch: 20
-> Acc = 0.5

Epoch: 21
-> Acc = 0.5

Epoch: 22
-> Acc = 0.5

Epoch: 23
-> Acc = 0.5

Epoch: 24
-> Acc = 0.5

Epoch: 25
-> Acc = 0.5

Epoch: 26
-> Acc = 0.5

Epoch: 27
-> Acc = 0.5

Epoch: 28
-> Acc = 0.5

Epoch: 29
-> Acc = 0.5

Epoch: 30
-> Acc = 0.5

Epoch: 31
-> Acc = 0.5

Epoch: 32
-> Acc = 0.5

Epoch: 33
-> Acc = 0.5

Epoch: 34
-> Acc = 0.5

Epoch: 35
-> Acc = 0.5

Epoch: 36
-> Acc = 0.5

Epoch: 37
-> Acc = 0.5

Epoch: 38
-> Acc = 0.5

Epoch: 39
-> Acc = 0.5

Epoch: 40
-> Acc = 0.5

Epoch: 41
-> Acc = 0.5

Epoch:

(array([[ 0.97454102, -1.03966513],
        [ 1.01914538, -0.95394317]]),
 array([[ 1.0327836, -1.0665118]]),
 array([[ 0.60441609, -0.27445414,  0.6036099 , -0.27068117,  0.60489362,
          0.60553857, -0.26955987, -0.27199438],
        [-0.21256282,  0.68390954, -0.21173553,  0.680039  , -0.21305148,
         -0.21371288,  0.67888929,  0.68138738]]),
 0.12825729254532564)

In [ ]:
#random data
data_x = np.random.randn(8, 2)
data_y = np.random.randint(0, 2, size=(8, 1))
data_rand = np.concatenate((data_x, data_y), axis=1)

w1_rand = np.random.randn(2, 2)
w2_rand = np.random.randn(1, 2)

b1_rand = np.random.randn()
b2_rand = np.random.randn()

print('\nRANDOM DATA:')
train(data_rand, w1_rand, w2_rand, b1_rand, b2_rand, 1000, 0.001)


RANDOM DATA:

Epoch: 1
-> Acc = 0.375

Epoch: 2
-> Acc = 0.375

Epoch: 3
-> Acc = 0.375

Epoch: 4
-> Acc = 0.375

Epoch: 5
-> Acc = 0.375

Epoch: 6
-> Acc = 0.375

Epoch: 7
-> Acc = 0.375

Epoch: 8
-> Acc = 0.375

Epoch: 9
-> Acc = 0.375

Epoch: 10
-> Acc = 0.375

Epoch: 11
-> Acc = 0.375

Epoch: 12
-> Acc = 0.375

Epoch: 13
-> Acc = 0.375

Epoch: 14
-> Acc = 0.375

Epoch: 15
-> Acc = 0.375

Epoch: 16
-> Acc = 0.375

Epoch: 17
-> Acc = 0.375

Epoch: 18
-> Acc = 0.375

Epoch: 19
-> Acc = 0.375

Epoch: 20
-> Acc = 0.375

Epoch: 21
-> Acc = 0.375

Epoch: 22
-> Acc = 0.375

Epoch: 23
-> Acc = 0.375

Epoch: 24
-> Acc = 0.375

Epoch: 25
-> Acc = 0.375

Epoch: 26
-> Acc = 0.375

Epoch: 27
-> Acc = 0.375

Epoch: 28
-> Acc = 0.375

Epoch: 29
-> Acc = 0.375

Epoch: 30
-> Acc = 0.375

Epoch: 31
-> Acc = 0.375

Epoch: 32
-> Acc = 0.375

Epoch: 33
-> Acc = 0.375

Epoch: 34
-> Acc = 0.375

Epoch: 35
-> Acc = 0.375

Epoch: 36
-> Acc = 0.375

Epoch: 37
-> Acc = 0.375

Epoch: 38
-> Acc = 0.375

Epoch:


Epoch: 603
-> Acc = 0.75

Epoch: 604
-> Acc = 0.75

Epoch: 605
-> Acc = 0.75

Epoch: 606
-> Acc = 0.75

Epoch: 607
-> Acc = 0.75

Epoch: 608
-> Acc = 0.75

Epoch: 609
-> Acc = 0.875

Epoch: 610
-> Acc = 0.875

Epoch: 611
-> Acc = 0.875

Epoch: 612
-> Acc = 0.875

Epoch: 613
-> Acc = 0.875

Epoch: 614
-> Acc = 0.875

Epoch: 615
-> Acc = 0.875

Epoch: 616
-> Acc = 0.875

Epoch: 617
-> Acc = 0.875

Epoch: 618
-> Acc = 0.875

Epoch: 619
-> Acc = 0.875

Epoch: 620
-> Acc = 0.875

Epoch: 621
-> Acc = 0.875

Epoch: 622
-> Acc = 0.875

Epoch: 623
-> Acc = 0.875

Epoch: 624
-> Acc = 0.875

Epoch: 625
-> Acc = 0.875

Epoch: 626
-> Acc = 0.875

Epoch: 627
-> Acc = 0.875

Epoch: 628
-> Acc = 0.875

Epoch: 629
-> Acc = 0.875

Epoch: 630
-> Acc = 0.875

Epoch: 631
-> Acc = 0.875

Epoch: 632
-> Acc = 0.875

Epoch: 633
-> Acc = 0.875

Epoch: 634
-> Acc = 0.875

Epoch: 635
-> Acc = 0.875

Epoch: 636
-> Acc = 0.875

Epoch: 637
-> Acc = 0.875

Epoch: 638
-> Acc = 0.875

Epoch: 639
-> Acc = 0.875

Epoch:


Epoch: 931
-> Acc = 1.0

Epoch: 932
-> Acc = 1.0

Epoch: 933
-> Acc = 1.0

Epoch: 934
-> Acc = 1.0

Epoch: 935
-> Acc = 1.0

Epoch: 936
-> Acc = 1.0

Epoch: 937
-> Acc = 1.0

Epoch: 938
-> Acc = 1.0

Epoch: 939
-> Acc = 1.0

Epoch: 940
-> Acc = 1.0

Epoch: 941
-> Acc = 1.0

Epoch: 942
-> Acc = 1.0

Epoch: 943
-> Acc = 1.0

Epoch: 944
-> Acc = 1.0

Epoch: 945
-> Acc = 1.0

Epoch: 946
-> Acc = 1.0

Epoch: 947
-> Acc = 1.0

Epoch: 948
-> Acc = 1.0

Epoch: 949
-> Acc = 1.0

Epoch: 950
-> Acc = 1.0

Epoch: 951
-> Acc = 1.0

Epoch: 952
-> Acc = 1.0

Epoch: 953
-> Acc = 1.0

Epoch: 954
-> Acc = 1.0

Epoch: 955
-> Acc = 1.0

Epoch: 956
-> Acc = 1.0

Epoch: 957
-> Acc = 1.0

Epoch: 958
-> Acc = 1.0

Epoch: 959
-> Acc = 1.0

Epoch: 960
-> Acc = 1.0

Epoch: 961
-> Acc = 1.0

Epoch: 962
-> Acc = 1.0

Epoch: 963
-> Acc = 1.0

Epoch: 964
-> Acc = 1.0

Epoch: 965
-> Acc = 1.0

Epoch: 966
-> Acc = 1.0

Epoch: 967
-> Acc = 1.0

Epoch: 968
-> Acc = 1.0

Epoch: 969
-> Acc = 1.0

Epoch: 970
-> Acc = 1.0


(array([[-0.18213775,  0.71101861],
        [ 0.45024531, -0.1590718 ]]),
 array([[2.22085576, 0.88998684]]),
 array([[-1.45978082, -1.49236847,  1.09675782, -1.48220723, -1.41643825,
         -1.36220739,  0.87948224,  1.31773045],
        [-0.52277976, -0.52413156,  0.66705161, -0.53393864, -0.50793602,
         -0.48604727,  0.56540099,  0.76481941]]),
 -1.276086305530933)